# SQL Server Docker 容器設定
# 使用 Microsoft 官方 SQL Server 2022 映像

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nl2sql-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd1234
      - MSSQL_PID=Developer

    ports:
      - "1433:1433"


    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
